version: '3'  
services: 
  jenkins:
     container_name: jenkins
     image: jenkins/jenkins
     ports: 
        - "80:8080" 
     volumes:
        -  "$PWD/jenkins_home:/var/jenkins_home"  
     networks: 
       - net
   
  remote_host:
     container_name: centos-host
     image: centos-host
     build: 
        context: centos
     volumes:
             - "$PWD/db-backup-s3.sh:/tmp/db_backup.sh"
     networks:
             - net    
  db_host:
     container_name: mysql-server
     image: mysql:5.7
     environment:
             - "MYSQL_ROOT_PASSWORD=admin"
     volumes:
             - "$PWD/db_data:/var/lib/mysql"
     networks:
             - net

networks:
        net:

